#!/bin/bash

# Prompt the user for the script name
read -p "Enter the file's name: " script_name

# Check if the script name is empty
if [ -z "$script_name" ]; then
    echo "Error: Script name cannot be empty."
    exit 1
fi

# Create the script file with the given script_name
echo "#include <stdio.h>" > "$script_name"

#adding 2 empty lines
echo "" >> "$script_name"
echo "/**" >> "$script_name"
echo " * main - integer" >> "$script_name"
echo " * Return: 0" >> "$script_name"
echo " */" >> "$script_name"
echo "int main(void)" >> "$script_name"
echo "{" >> "$script_name"
echo "" >> "$script_name"
echo -e "\treturn (0);" >> "$script_name"
echo "}" >> "$script_name"

vi  "$script_name"
# Prompt the user for the commit message
read -p "Enter the commit message: " commit_message

# Check if the commit message is empty
if [ -z "$commit_message" ]; then
    echo "Error: Commit message cannot be empty."
    exit 1
fi

# Perform the git add and commit with the provided message
git add .
git commit -m "$commit_message"
git push
